version: '3.3'
services:
  app:
    image: aibaribray/newssapi:latest
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres:latest
    platform: linux/x86_64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1402
      POSTGRES_DB: newsdb
    ports:
      - "5432:5432"
